version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "multi-language-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bdc2vjmpm90w"
s3_prefix = "multi-language-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StackName=\"MLN-Stack\" APIGatewayStageName=\"dev\""
